apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knx-homekit-bridge-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: knx-bridge.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: knx-homekit-bridge-service
            port:
              number: 8080